---
title:  Leave a Review | One Day Doors and Closets
timezone: UTC
exclude: 
- node_modules
- .jekyll-cache
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    is_dark: 
- scope:
    path: ''
    type: posts
  values:
    permalink: "/posts/:title/"
    layout: posts
email: jrandallwinton@gmail.com
description: Please take a few minutes to share your experience by posting a review for our business.
baseurl: 
url: https://onedayreviews.com
markdown: kramdown
sass:
  style: compressed
permalinks: pretty
plugins:
- jekyll-redirect-from
- jekyll-sitemap
