---
label: Default
hide_body: true
fields:
- name: hero_image
  type: file
  config:
    maxSize: 64
  label: Hero Image
- name: blocks
  type: blocks
  label: Blocks
  template_types:
  - heading
  - text-block
  config:
    min: 
    max: 
- name: page_type
  type: select
  default: []
  config:
    required: false
    options:
    - split
    - fullwidth
    source:
      type: simple
      section: 
      file: 
      path: 
  label: Page Type
pages:
- about.markdown
- index.markdown
