---
label: Default
hide_body: true
fields:
- name: page_title
  type: text
  config:
    required: false
  label: Page Title
  description: The title of the page.
- name: page_subtitle
  type: text
  config:
    required: false
  label: Page Subtitle
- name: page_content
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: true
    schema:
      format: markdown
  label: Content
- name: review_aggregate
  type: field_group_list
  fields:
  - name: label
    type: text
    config:
      required: false
    label: Label
    description: The label for the review aggregate i.e. Yelp, Google Business etc.
  - name: review_url
    type: text
    config:
      required: false
    label: Review URL
    description: Enter the URL to the review page.
  - name: button_label
    type: text
    config:
      required: false
    label: Button Label
    description: The label on the button. If nothing is entered, the default "Leave
      a Review" will be displayed.
  - name: svg
    type: textarea
    default: ''
    config:
      required: false
      wysiwyg: false
      schema:
        format: html
    label: SVG
    description: Paste the code for the SVG icon here.
  config:
    min: 
    max: 
    labelField: label
  label: Review Aggregate
pages:
- index.markdown
